url: https://www.staticgen.com
title: StaticGen
repo: https://github.com/netlify/staticgen
titleHome: StaticGen | Top Open Source Static Site Generators
subtitle: A List of Static Site Generators for JAMstack Sites
description: StaticGen is a leaderboard of the top open source static site generators. Promoting a static approach to building websites.
socialPreviewImageFilename: staticgen.png
shareButtons:
  - twitter
  - reddit
shareText: Check out StaticGen, a leaderboard of open source static site generators.
shareTextProjectStart: "Check out "
shareTextProjectEnd: ", an open source static site generator on the staticgen.com leaderboard."
copyrightName: Netlify
navLinks:
  - { url: https://jamstack.org, text: About JAMstack }
  - { url: https://headlesscms.org, text: Need a Static CMS? }
sorts:
  - { field: "stars", label: "GitHub stars", reverse: true }
  - { field: "followers", label: "Twitter followers", reverse: true }
  - { field: "title", label: "Title" }
filters:
  - { field: "language", emptyLabel: "Any Language", multiple: true }
  - { field: "templates", emptyLabel: "Any Template", multiple: true }
  - { field: "license", emptyLabel: "Any License", multiple: true }
fields:
  - { name: "language", label: "Languages" }
  - { name: "templates", label: "Templates" }
  - { name: "license", label: "License" }
